load('DataRicCurv2_Oct7_NatTwoR_CR_rmW.mat');
% check that the Ricci curvature tensor is correctly simplified.
Ric11 = RicCurv_in_aV(1,1);
test11 = Y^2*conj(dw_u)*(1/2*daV_u -3/2*conj(daV_conju))...
    +u*Y*(7*conj(daV_conju)-daV_u)*conj(w)...
    -(1/4*conj(dw_u)^2 +4*conj(dw_vnormv) +8*conj(aV)*conj(w))...
    +u/Y*conj(w)*conj(dw_u) - u^2/Y^2*conj(w)^2 ...
    +Y^4*(2*theta+i*aV-i*conj(aV))*(-2*i*d2aV_uu)...
    +Y^3*(2*theta+i*aV-i*conj(aV))*(-4*i*conj(u)*daV_u)...
    -Y^4/4*(daV_u+conj(daV_conju))^2 +2*Y^2*conj(d2aV_conjuMu);

diff11 = Ric11-test11;
diff11 = complex_simple3(diff11,MVarRicCurv2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ric12 = RicCurv_in_aV(1,2);

test12One = Y^2/12*d2w_uu*(aV-2*i*theta-conj(aV))...
    +Y^2/12*conj(d2w_uu)*(2*i*theta-aV+conj(aV))...
    +Y^2/4*(daV_u-conj(daV_conju))*dw_u...
    +Y^2/4*(-daV_conju+conj(daV_u))*conj(dw_u)...
    +Y*conj(u)*dw_u*(i*theta-aV/2+conj(aV)/2)...
    +Y*u*conj(dw_u)*(aV/2-conj(aV)/2-i*theta)...
    +Y*conj(u)*w*(-3/2*daV_u+1/2*conj(daV_conju))...
    +Y*u*conj(w)*(1/2*daV_conju-3/2*conj(daV_u))...
    +1/4*dw_u*conj(dw_u) -1/2*d2w_uconjMu -1/2*conj(d2w_uconjMu)...
    +conj(u)^2*w*(aV-2*i*theta-conj(aV))...
    +u^2*conj(w)*(-aV+conj(aV)+2*i*theta)...
    +2*conj(u)/Y*dw_conjMu +2*u/Y*conj(dw_conjMu) +1/Y*w*conj(w)...
    -1/(2*Y)*(conj(u)*w*conj(dw_u) +u*conj(w)*dw_u)...
    +1/Y^2*w*conj(w);

test12Two = Y^4*(1/4*daV_conju*conj(daV_conju) -3/4*daV_u*conj(daV_u))...
    -Y^4*(3/4*daV_u*daV_conju) +Y^4/4*conj(daV_u)*conj(daV_conju)...
    +Y^2/2*(d2aV_uMu +conj(d2aV_uMu))...
    +Y^2*(d2aV_conjuconjMu -daV_vnormv + conj(daV_vnormv))...
    +Y^2*(2*i*dtheta_vnormv -20*theta^2/3 -22*i/3*theta*aV...
        +34*i/3*theta*conj(aV) -6*aV*conj(aV) +2*aV^2 +4*conj(aV)^2 );
    
diff12 = Ric12 - test12One - test12Two;
diff12 = complex_simple3(diff12,MVarRicCurv2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ric16 = RicCurv_in_aV(1,6);

test16 = i/4*conj(dw_u)- i/(2*Y)*u*conj(w) -i*Y^2/4*(daV_u+conj(daV_conju));
diff16 = Ric16 - test16;
diff16 = complex_simple3(diff16,MVarRicCurv2);

Ric34 = RicCurv_in_aV(3,4);
diff34 = Ric34 - (Y+1)/Y^2;
diff34 = complex_simple3(diff34,MVarRicCurv2);

disp(RicCurv_in_aV(6,6))
disp(RicCurv_in_aV(4,6))
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ric14 = RicCurv_in_aV(1,4);

test14 = 1/12*d2w_uu -7/12*conj(d2w_uu) -1/(2*Y)*conj(u)*dw_u...
    +3/Y*u*conj(dw_u) +1/Y^2*conj(u)^2*w -6/Y^2*u^2*conj(w)...
    +1/(12*Y^2)*6*u*Y^3*(daV_u +conj(daV_conju))...
    +1/12*(-40*i*theta +24*aV - 48*conj(aV));
diff14 = Ric14 - test14;
diff14 = complex_simple3(diff14,MVarRicCurv2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ric56 = RicCurv_in_aV(5,6);

test56= -i/48*conj(d2w_uu) +    i/48*d2w_uu -1/(8*Y)*i*conj(u)*dw_u...
    +1/(8*Y)*i*u*conj(dw_u) +1/(4*Y^2)*i*conj(u)^2*w...
    -1/(4*Y^2)*i*u^2*conj(w)...
    +Y/48*(-12*i*conj(u)*daV_conju +12*i*u*conj(daV_conju))...
    +1/48*(36*i*aV +40*theta -36*i*conj(aV));

diff56 = Ric56 -test56;
diff56 = complex_simple3(diff56,MVarRicCurv2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
disp(RicCurv_in_aV(3,3))

Ric13 = RicCurv_in_aV(1,3);

test13 = -1/(2*Y^2)*(-conj(u)*Y*conj(dw_u) +2*Y*conj(w) -10*conj(w)...
        +4*Y^4*d2aV_uu +9*conj(u)*Y^3*daV_u +conj(u)*Y^3*conj(daV_conju));
diff13 = Ric13 -test13;
diff13 = complex_simple3(diff13,MVarRicCurv2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Ric15 = RicCurv_in_aV(1,5);

test15One = Y^5*(1/48*daV_u*d2w_uu +1/2*d2aV_uu*dw_u...
    -1/48*daV_u*conj(d2w_uu) +1/48*conj(daV_conju)*d2w_uu...
    -25/48*conj(daV_conju)*conj(d2w_uu) )...
    +Y^4*(-1/2*daV_conju*conj(w) +7/8*conj(u)*daV_u*dw_u...
    +1/8*u*daV_u*conj(dw_u) -2*conj(u)*d2aV_uu*w +1/4*conj(u)*daV_conju*conj(dw_u)...
    -1/8*conj(u)*conj(daV_conju)*dw_u +23/8*u*conj(daV_conju)*conj(dw_u))...
    +Y^3*(1/12*conj(d3w_uuMu)-1/12*d3w_uuconjMu -conj(d2w_uvnormv)...
    +1/12*conj(w)*conj(d3w_uuu) -3/4*aV*conj(dw_u)-1/48*conj(dw_u)*d2w_uu...
    +5/2*daV_conju*conj(w) -1/4*conj(aV)*conj(dw_u)...
    +1/48*conj(dw_u)*conj(d2w_uu) -15/4*conj(u)^2*daV_u*w...
    -1/4*u^2*daV_u*conj(w) +1/4*conj(u)^2*conj(daV_conju)*w...
    -23/4*u^2*conj(daV_conju)*conj(w) +5*i*theta/6*conj(dw_u))...
    +Y^2*(-1/8*u*conj(dw_u)^2 +1/8*conj(u)*dw_u*conj(dw_u)...
    -1/2*u*conj(d2w_uMu) +1/2*conj(u)*d2w_uconjMu +4*u*conj(dw_vnormv)...
    -1/4*conj(w)*dw_u +3/2*u*aV*conj(w) +1/24*u*conj(w)*d2w_uu...
    -5*i*theta/3*u*conj(w) +5/2*u*conj(aV)*conj(w) -13/24*u*conj(w)*conj(d2w_uu))...
    +Y*(u^2*conj(dw_Mu) -1/4*conj(w)*dw_u -conj(u)^2*dw_conjMu...
    +1/2*conj(u)*w*conj(w) -1/4*conj(u)^2*w*conj(dw_u) +2*u^2*conj(w)*conj(dw_u))...
    +3*conj(u)/2*w*conj(w) -(5*u^3)/2*conj(w)^2;

test15Two = Y^7*(-5/4*d2aV_uu*daV_conju -5/4*d2aV_uu*conj(daV_u))...
    +Y^6*(1/4*u*conj(daV_conju)^2 -11/4*conj(u)*daV_u*daV_conju...
    +u/4*daV_u*conj(daV_conju) -5/2*conj(u)*daV_u*conj(daV_u)...
    -1/4*conj(u)*daV_conju*conj(daV_conju))...
    +Y^5*(3/4*d3aV_uuMu -1/2*d2aV_uvnormv +conj(d2aV_conjuvnormv)...
    +3/4*aV*daV_u -5/4*conj(aV)*daV_u +5/4*aV*conj(daV_conju)...
    -3/4*conj(aV)*conj(daV_conju) -5*i/6*theta*conj(daV_conju)...
    -5*i/6*theta*daV_u)...
    +Y^4*(3/2)*conj(u)*d2aV_uMu...
    +Y^3*(-1/2*daV_conjMu -conj(daV_Mu) -2*i/3*conj(dtheta_Mu));


diff15= Ric15 -1/Y^3*(test15One + test15Two);
diff15 = complex_simple3(diff15,MVarRicCurv2);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Ric35 = RicCurv_in_aV(3,5);
test35 = -1/12*d3w_uuu +13/(24*Y)*conj(u)*d2w_uu...
    -1/(24*Y)*conj(u)*conj(d2w_uu) +1/(4*Y)*conj(dw_u)...
    +1/(4*Y^2)*conj(dw_u) -7/(4*Y^2)*conj(u)^2*dw_u...
    -1/(2*Y^2)*u*conj(w) -3/(2*Y^3)*u*conj(w)...
    +5/(2*Y^3)*conj(u)^3*w...
    -1/2*conj(daV_conju) +1/2*Y*conj(daV_conju) +3/(2*Y)*conj(u)*aV...
    -1/2*conj(u)^2*daV_conju -3/(2*Y)*conj(u)*conj(aV)...
    -5/(3*Y)*i*conj(u)*theta;

diff35= Ric35 -test35;
diff35 = complex_simple3(diff35,MVarRicCurv2);


% load('DataRicCurv2_Oct7_NatTwoR_CR_rmW.mat');
% Ry55 = Y^4*RicCurv_in_aV(5,5);
% [termVec, yVec] = coeffs(Ry55,[Y,conj(Y)]);
% 
% latexFile = fopen('latex_RicCurv55.tex','w');
% fprintf(latexFile, '\\documentclass{article}[10pt,a4paper] \n');
% fprintf(latexFile, '\\begin{document}\n');
% fprintf(latexFile, '\\thispagestyle{empty} \n');
% fprintf(latexFile, '%s\n', ' ');
% fprintf(latexFile, '\\hfill {\\it Date: %s}\n', string(date));
% fprintf(latexFile, '\\begin{center}');
% fprintf(latexFile, '{\\bf The $Y^4\\cot \\mbox{Ric}(5,5)$ }');
% fprintf(latexFile, '\\end{center} \n');
% fprintf(latexFile, '%s\n', ' ');
% 
% for j=1:length(yVec)
%     fprintf(latexFile,'term: \\mbox{ } $ %s $: \\\\ \n',latex(yVec(j)));
%     fprintf(latexFile, '%s\n', ' ');
%     fprintf(latexFile,'$\\displaystyle %s $ \\\\[0.1in] \n',latex(termVec(j)));
%     fprintf(latexFile, '%s\n', ' ');
% end
% 
% fprintf(latexFile, '\\end{document}]\n');
% fclose(latexFile);
% 
% % command = 'pdflatex latex_RicCurv55.tex';
% % [status,cmdout] = system(command);






















